%llguidance {}

BOOLEAN: ("true" | "false") SPACE

CHAR: /[^"\\\x7F\x00-\x1F]/
     | /[\\]/ (/["\\bfnrt]/ | "u" /[0-9a-fA-F]/{4,4})

IS_MEMBER_KV: "\"isMember\"" SPACE ":" SPACE BOOLEAN
MEMBERSHIP_NUMBER_KV: "\"membershipNumber\"" SPACE ":" SPACE STRING
start: SPACE  "{" SPACE IS_MEMBER_KV ("," SPACE MEMBERSHIP_NUMBER_KV)? "}" SPACE FENCE?
SPACE: /[ \t\n\r]/*
STRING: "\"" CHAR* "\"" SPACE
FENCE: "```"
