%llguidance {}

BUDGET_KV: "\"budget\"" SPACE ":" SPACE NUMBER

CHAR: /[^"\\\x7F\x00-\x1F]/
     | /[\\]/ (/["\\bfnrt]/ | "u" /[0-9a-fA-F]/{4,4})

DECIMAL_PART: /[0-9]/{1,16}

INTEGRAL_PART: /[0]/
     | /[1-9]/ /[0-9]/{0,15}

NUMBER: "-"? INTEGRAL_PART ("." DECIMAL_PART)? (/[eE]/ /[-+]/? INTEGRAL_PART)? SPACE
PROJECT_ID_KV: "\"projectId\"" SPACE ":" SPACE STRING
PROJECT_LEAD_KV: "\"projectLead\"" SPACE ":" SPACE STRING
PROJECT_NAME_KV: "\"projectName\"" SPACE ":" SPACE STRING
start: SPACE  "{" SPACE PROJECT_ID_KV "," SPACE PROJECT_NAME_KV "," SPACE BUDGET_KV "," SPACE PROJECT_LEAD_KV "}" SPACE FENCE?
SPACE: /[ \t\n\r]/*
STRING: "\"" CHAR* "\"" SPACE
FENCE: "```"
