%llguidance {}

CHAR: /[^"\\\x7F\x00-\x1F]/
     | /[\\]/ (/["\\bfnrt]/ | "u" /[0-9a-fA-F]/{4,4})

CLOSING_TIME: "\"" (/[0-1]/? /[0-9]/ | "2" /[0-3]/) ":" /[0-5]/ /[0-9]/ "\"" SPACE
CLOSING_TIME_KV: "\"closingTime\"" SPACE ":" SPACE CLOSING_TIME
DAYS_OPEN: "[" SPACE (DAYS_OPEN_ITEM ("," SPACE DAYS_OPEN_ITEM)*)? "]" SPACE
DAYS_OPEN_ITEM: ("\"Monday\"" | "\"Tuesday\"" | "\"Wednesday\"" | "\"Thursday\"" | "\"Friday\"" | "\"Saturday\"" | "\"Sunday\"") SPACE
DAYS_OPEN_KV: "\"daysOpen\"" SPACE ":" SPACE DAYS_OPEN
OPENING_TIME: "\"" (/[0-1]/? /[0-9]/ | "2" /[0-3]/) ":" /[0-5]/ /[0-9]/ "\"" SPACE
OPENING_TIME_KV: "\"openingTime\"" SPACE ":" SPACE OPENING_TIME
start: SPACE  "{" SPACE STORE_ID_KV "," SPACE OPENING_TIME_KV "," SPACE CLOSING_TIME_KV "," SPACE DAYS_OPEN_KV "}" SPACE FENCE?
SPACE: /[ \t\n\r]/*
STORE_ID_KV: "\"storeID\"" SPACE ":" SPACE STRING
STRING: "\"" CHAR* "\"" SPACE
FENCE: "```"
