%llguidance {}

AVAILABILITY_KV: "\"availability\"" SPACE ":" SPACE BOOLEAN
BOOLEAN: ("true" | "false") SPACE

CHAR: /[^"\\\x7F\x00-\x1F]/
     | /[\\]/ (/["\\bfnrt]/ | "u" /[0-9a-fA-F]/{4,4})

DECIMAL_PART: /[0-9]/{1,16}
GAME_ID_KV: "\"gameId\"" SPACE ":" SPACE STRING

INTEGRAL_PART: /[0]/
     | /[1-9]/ /[0-9]/{0,15}

NUMBER: "-"? INTEGRAL_PART ("." DECIMAL_PART)? (/[eE]/ /[-+]/? INTEGRAL_PART)? SPACE
PLATFORM: "[" SPACE (STRING ("," SPACE STRING)*)? "]" SPACE
PLATFORM_KV: "\"platform\"" SPACE ":" SPACE PLATFORM
PRICE_KV: "\"price\"" SPACE ":" SPACE NUMBER
start: SPACE  "{" SPACE GAME_ID_KV "," SPACE TITLE_KV "," SPACE PLATFORM_KV "," SPACE AVAILABILITY_KV "," SPACE PRICE_KV "}" SPACE FENCE?
SPACE: /[ \t\n\r]/*
STRING: "\"" CHAR* "\"" SPACE
TITLE_KV: "\"title\"" SPACE ":" SPACE STRING
FENCE: "```"
