%llguidance {}

CHAR: /[^"\\\x7F\x00-\x1F]/
     | /[\\]/ (/["\\bfnrt]/ | "u" /[0-9a-fA-F]/{4,4})

COMMENTS_KV: "\"comments\"" SPACE ":" SPACE STRING
CUSTOMER_ID_KV: "\"customerID\"" SPACE ":" SPACE STRING
DATE: /[0-9]/{4,4} "-" ("0" /[1-9]/ | "1" /[0-2]/) "-" ("0" /[1-9]/ | /[1-2]/ /[0-9]/ | "3" /[0-1]/)
DATE_TIME: DATE "T" TIME
DATE_TIME_STRING: "\"" DATE_TIME "\"" SPACE
FEEDBACK_ID_KV: "\"feedbackID\"" SPACE ":" SPACE STRING
start: SPACE  "{" SPACE FEEDBACK_ID_KV "," SPACE CUSTOMER_ID_KV "," SPACE SERVICE_RATING_KV "," SPACE COMMENTS_KV "," SPACE SUBMISSION_DATE_KV "}" SPACE FENCE?
SERVICE_RATING: /[1-5]/ SPACE
SERVICE_RATING_KV: "\"serviceRating\"" SPACE ":" SPACE SERVICE_RATING
SPACE: /[ \t\n\r]/*
STRING: "\"" CHAR* "\"" SPACE
SUBMISSION_DATE: DATE_TIME_STRING
SUBMISSION_DATE_KV: "\"submissionDate\"" SPACE ":" SPACE SUBMISSION_DATE
TIME: (/[01]/ /[0-9]/ | "2" /[0-3]/) ":" /[0-5]/ /[0-9]/ ":" /[0-5]/ /[0-9]/ ("." /[0-9]/{3,3})? ("Z" | ("+" | "-") (/[01]/ /[0-9]/ | "2" /[0-3]/) ":" /[0-5]/ /[0-9]/)
FENCE: "```"
