%llguidance {}

CHAR: /[^"\\\x7F\x00-\x1F]/
     | /[\\]/ (/["\\bfnrt]/ | "u" /[0-9a-fA-F]/{4,4})

EMAIL_KV: "\"email\"" SPACE ":" SPACE STRING
NAME_KV: "\"name\"" SPACE ":" SPACE STRING
start: SPACE  "{" SPACE NAME_KV "," SPACE EMAIL_KV "," SPACE SHIPPING_ADDRESS_KV "}" SPACE FENCE?
SHIPPING_ADDRESS_KV: "\"shippingAddress\"" SPACE ":" SPACE STRING
SPACE: /[ \t\n\r]/*
STRING: "\"" CHAR* "\"" SPACE
FENCE: "```"
