%llguidance {}

CHAR: /[^"\\\x7F\x00-\x1F]/
     | /[\\]/ (/["\\bfnrt]/ | "u" /[0-9a-fA-F]/{4,4})

DATE: /[0-9]/{4,4} "-" ("0" /[1-9]/ | "1" /[0-2]/) "-" ("0" /[1-9]/ | /[1-2]/ /[0-9]/ | "3" /[0-1]/)
DATE_TIME: DATE "T" TIME
DATE_TIME_STRING: "\"" DATE_TIME "\"" SPACE
GUEST_NAME_KV: "\"guestName\"" SPACE ":" SPACE STRING
RESERVATION_ID_KV: "\"reservationID\"" SPACE ":" SPACE STRING
RESERVATION_TIME: DATE_TIME_STRING
RESERVATION_TIME_KV: "\"reservationTime\"" SPACE ":" SPACE RESERVATION_TIME
start: SPACE  "{" SPACE RESERVATION_ID_KV "," SPACE GUEST_NAME_KV "," SPACE RESERVATION_TIME_KV ("," SPACE SPECIAL_REQUESTS_KV)? "}" SPACE FENCE?
SPACE: /[ \t\n\r]/*
SPECIAL_REQUESTS: "[" SPACE (STRING ("," SPACE STRING)*)? "]" SPACE
SPECIAL_REQUESTS_KV: "\"specialRequests\"" SPACE ":" SPACE SPECIAL_REQUESTS
STRING: "\"" CHAR* "\"" SPACE
TIME: (/[01]/ /[0-9]/ | "2" /[0-3]/) ":" /[0-5]/ /[0-9]/ ":" /[0-5]/ /[0-9]/ ("." /[0-9]/{3,3})? ("Z" | ("+" | "-") (/[01]/ /[0-9]/ | "2" /[0-3]/) ":" /[0-5]/ /[0-9]/)
FENCE: "```"
