%llguidance {}

CAPACITY_KV: "\"capacity\"" SPACE ":" SPACE STRING

CHAR: /[^"\\\x7F\x00-\x1F]/
     | /[\\]/ (/["\\bfnrt]/ | "u" /[0-9a-fA-F]/{4,4})

DECIMAL_PART: /[0-9]/{1,16}
DIMENSIONS_KV: "\"dimensions\"" SPACE ":" SPACE STRING

INTEGRAL_PART: /[0]/
     | /[1-9]/ /[0-9]/{0,15}

NUMBER: "-"? INTEGRAL_PART ("." DECIMAL_PART)? (/[eE]/ /[-+]/? INTEGRAL_PART)? SPACE
start: SPACE  "{" SPACE TYPE_KV "," SPACE VOLTAGE_KV "," SPACE CAPACITY_KV "," SPACE DIMENSIONS_KV "}" SPACE FENCE?
SPACE: /[ \t\n\r]/*
STRING: "\"" CHAR* "\"" SPACE
TYPE_KV: "\"type\"" SPACE ":" SPACE STRING
VOLTAGE_KV: "\"voltage\"" SPACE ":" SPACE NUMBER
FENCE: "```"
