%llguidance {}

CHAR: /[^"\\\x7F\x00-\x1F]/
     | /[\\]/ (/["\\bfnrt]/ | "u" /[0-9a-fA-F]/{4,4})

DRUG_ID_KV: "\"drugID\"" SPACE ":" SPACE STRING
LOCATION_KV: "\"location\"" SPACE ":" SPACE STRING
QUANTITY_AVAILABLE: (/[0]/ | /[1-9]/ /[0-9]/{0,15}) SPACE
QUANTITY_AVAILABLE_KV: "\"quantityAvailable\"" SPACE ":" SPACE QUANTITY_AVAILABLE
REORDER_THRESHOLD: (/[0]/ | /[1-9]/ /[0-9]/{0,15}) SPACE
REORDER_THRESHOLD_KV: "\"reorderThreshold\"" SPACE ":" SPACE REORDER_THRESHOLD
start: SPACE  "{" SPACE DRUG_ID_KV "," SPACE QUANTITY_AVAILABLE_KV "," SPACE LOCATION_KV "," SPACE REORDER_THRESHOLD_KV "}" SPACE FENCE?
SPACE: /[ \t\n\r]/*
STRING: "\"" CHAR* "\"" SPACE
FENCE: "```"
