%llguidance {}

SKU_KV: "\"SKU\"" SPACE ":" SPACE STRING

CHAR: /[^"\\\x7F\x00-\x1F]/
     | /[\\]/ (/["\\bfnrt]/ | "u" /[0-9a-fA-F]/{4,4})

DATE: /[0-9]/{4,4} "-" ("0" /[1-9]/ | "1" /[0-2]/) "-" ("0" /[1-9]/ | /[1-2]/ /[0-9]/ | "3" /[0-1]/)
DATE_STRING: "\"" DATE "\"" SPACE
INTEGER: "-"? INTEGRAL_PART SPACE

INTEGRAL_PART: /[0]/
     | /[1-9]/ /[0-9]/{0,15}

QUANTITY_KV: "\"quantity\"" SPACE ":" SPACE INTEGER
RESTOCK_DATE: DATE_STRING
RESTOCK_DATE_KV: "\"restockDate\"" SPACE ":" SPACE RESTOCK_DATE
start: SPACE  "{" SPACE SKU_KV "," SPACE QUANTITY_KV "," SPACE RESTOCK_DATE_KV "," SPACE SUPPLIER_KV "}" SPACE FENCE?
SPACE: /[ \t\n\r]/*
STRING: "\"" CHAR* "\"" SPACE
SUPPLIER_KV: "\"supplier\"" SPACE ":" SPACE STRING
FENCE: "```"
