%llguidance {}

CHAR: /[^"\\\x7F\x00-\x1F]/
     | /[\\]/ (/["\\bfnrt]/ | "u" /[0-9a-fA-F]/{4,4})

DATE: /[0-9]/{4,4} "-" ("0" /[1-9]/ | "1" /[0-2]/) "-" ("0" /[1-9]/ | /[1-2]/ /[0-9]/ | "3" /[0-1]/)
DATE_STRING: "\"" DATE "\"" SPACE
EXPIRATION_DATE: DATE_STRING
EXPIRATION_DATE_KV: "\"expirationDate\"" SPACE ":" SPACE EXPIRATION_DATE
ISSUE_DATE: DATE_STRING
ISSUE_DATE_KV: "\"issueDate\"" SPACE ":" SPACE ISSUE_DATE
LICENSE_KEY_KV: "\"licenseKey\"" SPACE ":" SPACE STRING
LICENSE_TYPE_KV: "\"licenseType\"" SPACE ":" SPACE STRING
start: SPACE  "{" SPACE LICENSE_KEY_KV "," SPACE SOFTWARE_NAME_KV "," SPACE LICENSE_TYPE_KV "," SPACE ISSUE_DATE_KV "," SPACE EXPIRATION_DATE_KV "}" SPACE FENCE?
SOFTWARE_NAME_KV: "\"softwareName\"" SPACE ":" SPACE STRING
SPACE: /[ \t\n\r]/*
STRING: "\"" CHAR* "\"" SPACE
FENCE: "```"
