%llguidance {}

CHAR: /[^"\\\x7F\x00-\x1F]/
     | /[\\]/ (/["\\bfnrt]/ | "u" /[0-9a-fA-F]/{4,4})

ITEM_ID_KV: "\"itemId\"" SPACE ":" SPACE STRING
ITEM_NAME_KV: "\"itemName\"" SPACE ":" SPACE STRING
QUANTITY: (/[0]/ | /[1-9]/ /[0-9]/{0,15}) SPACE
QUANTITY_KV: "\"quantity\"" SPACE ":" SPACE QUANTITY
REORDER_LEVEL: (/[0]/ | /[1-9]/ /[0-9]/{0,15}) SPACE
REORDER_LEVEL_KV: "\"reorderLevel\"" SPACE ":" SPACE REORDER_LEVEL
start: SPACE  "{" SPACE ITEM_ID_KV "," SPACE ITEM_NAME_KV "," SPACE QUANTITY_KV "," SPACE REORDER_LEVEL_KV "}" SPACE FENCE?
SPACE: /[ \t\n\r]/*
STRING: "\"" CHAR* "\"" SPACE
FENCE: "```"
