%llguidance {}

CHAR: /[^"\\\x7F\x00-\x1F]/
     | /[\\]/ (/["\\bfnrt]/ | "u" /[0-9a-fA-F]/{4,4})

DECIMAL_PART: /[0-9]/{1,16}

INTEGRAL_PART: /[0]/
     | /[1-9]/ /[0-9]/{0,15}

ITEM: "{" SPACE ITEM_FUEL_TYPE_KV "," SPACE ITEM_QUANTITY_IN_STOCK_KV "," SPACE ITEM_REORDER_LEVEL_KV "}" SPACE
ITEM_FUEL_TYPE_KV: "\"fuelType\"" SPACE ":" SPACE STRING
ITEM_QUANTITY_IN_STOCK_KV: "\"quantityInStock\"" SPACE ":" SPACE NUMBER
ITEM_REORDER_LEVEL_KV: "\"reorderLevel\"" SPACE ":" SPACE NUMBER
NUMBER: "-"? INTEGRAL_PART ("." DECIMAL_PART)? (/[eE]/ /[-+]/? INTEGRAL_PART)? SPACE
start: SPACE  "[" SPACE (ITEM ("," SPACE ITEM)*)? "]" SPACE FENCE?
SPACE: /[ \t\n\r]/*
STRING: "\"" CHAR* "\"" SPACE
FENCE: "```"
