%llguidance {}

CHAR: /[^"\\\x7F\x00-\x1F]/
     | /[\\]/ (/["\\bfnrt]/ | "u" /[0-9a-fA-F]/{4,4})

COMMENTS_KV: "\"comments\"" SPACE ":" SPACE STRING
CUSTOMER_ID_KV: "\"customerID\"" SPACE ":" SPACE STRING
FEEDBACK_ID_KV: "\"feedbackID\"" SPACE ":" SPACE STRING
PRODUCT_ID_KV: "\"productID\"" SPACE ":" SPACE STRING
RATING: /[1-5]/ SPACE
RATING_KV: "\"rating\"" SPACE ":" SPACE RATING
start: SPACE  "{" SPACE FEEDBACK_ID_KV "," SPACE CUSTOMER_ID_KV "," SPACE PRODUCT_ID_KV "," SPACE RATING_KV ("," SPACE COMMENTS_KV)? "}" SPACE FENCE?
SPACE: /[ \t\n\r]/*
STRING: "\"" CHAR* "\"" SPACE
FENCE: "```"
