%llguidance {}

CHAR: /[^"\\\x7F\x00-\x1F]/
     | /[\\]/ (/["\\bfnrt]/ | "u" /[0-9a-fA-F]/{4,4})

INTEGER: "-"? INTEGRAL_PART SPACE

INTEGRAL_PART: /[0]/
     | /[1-9]/ /[0-9]/{0,15}

ITEM_ID_KV: "\"itemID\"" SPACE ":" SPACE STRING
ITEM_NAME_KV: "\"itemName\"" SPACE ":" SPACE STRING
QUANTITY_AVAILABLE_KV: "\"quantityAvailable\"" SPACE ":" SPACE INTEGER
REORDER_THRESHOLD_KV: "\"reorderThreshold\"" SPACE ":" SPACE INTEGER
start: SPACE  "{" SPACE ITEM_ID_KV "," SPACE ITEM_NAME_KV "," SPACE QUANTITY_AVAILABLE_KV "," SPACE REORDER_THRESHOLD_KV "}" SPACE FENCE?
SPACE: /[ \t\n\r]/*
STRING: "\"" CHAR* "\"" SPACE
FENCE: "```"
