%llguidance {}

CHAR: /[^"\\\x7F\x00-\x1F]/
     | /[\\]/ (/["\\bfnrt]/ | "u" /[0-9a-fA-F]/{4,4})

DATA: INTEGER
     | STRING
     | NULL
     | DATA_3

DATA_3: "[" SPACE (INTEGER ("," SPACE INTEGER)*)? "]" SPACE
DATA_KV: "\"data\"" SPACE ":" SPACE DATA
INTEGER: "-"? INTEGRAL_PART SPACE

INTEGRAL_PART: /[0]/
     | /[1-9]/ /[0-9]/{0,15}

NULL: "null" SPACE
start: SPACE  "{" SPACE DATA_KV? "}" SPACE FENCE?
SPACE: /[ \t\n\r]/*
STRING: "\"" CHAR* "\"" SPACE
FENCE: "```"
