%llguidance {}

CHAR: /[^"\\\x7F\x00-\x1F]/
     | /[\\]/ (/["\\bfnrt]/ | "u" /[0-9a-fA-F]/{4,4})

COLOR_KV: "\"color\"" SPACE ":" SPACE STRING
DECIMAL_PART: /[0-9]/{1,16}

INTEGRAL_PART: /[0]/
     | /[1-9]/ /[0-9]/{0,15}

ITEM_ID_KV: "\"itemID\"" SPACE ":" SPACE STRING
ITEM_NAME_KV: "\"itemName\"" SPACE ":" SPACE STRING
NUMBER: "-"? INTEGRAL_PART ("." DECIMAL_PART)? (/[eE]/ /[-+]/? INTEGRAL_PART)? SPACE
PRICE_KV: "\"price\"" SPACE ":" SPACE NUMBER
start: SPACE  "{" SPACE ITEM_ID_KV "," SPACE ITEM_NAME_KV "," SPACE SIZE_KV "," SPACE COLOR_KV "," SPACE PRICE_KV "}" SPACE FENCE?
SIZE_KV: "\"size\"" SPACE ":" SPACE STRING
SPACE: /[ \t\n\r]/*
STRING: "\"" CHAR* "\"" SPACE
FENCE: "```"
