%llguidance {}

CHAR: /[^"\\\x7F\x00-\x1F]/
     | /[\\]/ (/["\\bfnrt]/ | "u" /[0-9a-fA-F]/{4,4})

INTEGER: "-"? INTEGRAL_PART SPACE

INTEGRAL_PART: /[0]/
     | /[1-9]/ /[0-9]/{0,15}

ITEM_CATEGORY_KV: "\"itemCategory\"" SPACE ":" SPACE STRING
ITEM_ID_KV: "\"itemID\"" SPACE ":" SPACE STRING
ITEM_NAME_KV: "\"itemName\"" SPACE ":" SPACE STRING
QUANTITY_KV: "\"quantity\"" SPACE ":" SPACE INTEGER
start: SPACE  "{" SPACE ITEM_ID_KV "," SPACE ITEM_NAME_KV "," SPACE ITEM_CATEGORY_KV "," SPACE QUANTITY_KV "," SPACE SUPPLIER_KV "}" SPACE FENCE?
SPACE: /[ \t\n\r]/*
STRING: "\"" CHAR* "\"" SPACE
SUPPLIER_KV: "\"supplier\"" SPACE ":" SPACE STRING
FENCE: "```"
