%llguidance {}

ACTIVATION_DATE: DATE_STRING
ACTIVATION_DATE_KV: "\"activationDate\"" SPACE ":" SPACE ACTIVATION_DATE

CHAR: /[^"\\\x7F\x00-\x1F]/
     | /[\\]/ (/["\\bfnrt]/ | "u" /[0-9a-fA-F]/{4,4})

DATE: /[0-9]/{4,4} "-" ("0" /[1-9]/ | "1" /[0-2]/) "-" ("0" /[1-9]/ | /[1-2]/ /[0-9]/ | "3" /[0-1]/)
DATE_STRING: "\"" DATE "\"" SPACE
PHONE_NUMBER_KV: "\"phoneNumber\"" SPACE ":" SPACE STRING
PLAN_TYPE_KV: "\"planType\"" SPACE ":" SPACE STRING
start: SPACE  "{" SPACE SUBSCRIBER_ID_KV "," SPACE PHONE_NUMBER_KV "," SPACE PLAN_TYPE_KV "," SPACE ACTIVATION_DATE_KV "}" SPACE FENCE?
SPACE: /[ \t\n\r]/*
STRING: "\"" CHAR* "\"" SPACE
SUBSCRIBER_ID_KV: "\"subscriberID\"" SPACE ":" SPACE STRING
FENCE: "```"
