%llguidance {}

CHAR: /[^"\\\x7F\x00-\x1F]/
     | /[\\]/ (/["\\bfnrt]/ | "u" /[0-9a-fA-F]/{4,4})

DATE: /[0-9]/{4,4} "-" ("0" /[1-9]/ | "1" /[0-2]/) "-" ("0" /[1-9]/ | /[1-2]/ /[0-9]/ | "3" /[0-1]/)
DATE_TIME: DATE "T" TIME
DATE_TIME_STRING: "\"" DATE_TIME "\"" SPACE
DECIMAL_PART: /[0-9]/{1,16}
DEVICE_ID_KV: "\"deviceID\"" SPACE ":" SPACE STRING

INTEGRAL_PART: /[0]/
     | /[1-9]/ /[0-9]/{0,15}

METRICS: "{" SPACE METRICS_HEART_RATE_KV "," SPACE METRICS_BLOOD_PRESSURE_KV "," SPACE METRICS_OXYGEN_SATURATION_KV "}" SPACE
METRICS_BLOOD_PRESSURE_KV: "\"bloodPressure\"" SPACE ":" SPACE STRING
METRICS_HEART_RATE_KV: "\"heartRate\"" SPACE ":" SPACE NUMBER
METRICS_KV: "\"metrics\"" SPACE ":" SPACE METRICS
METRICS_OXYGEN_SATURATION_KV: "\"oxygenSaturation\"" SPACE ":" SPACE NUMBER
NUMBER: "-"? INTEGRAL_PART ("." DECIMAL_PART)? (/[eE]/ /[-+]/? INTEGRAL_PART)? SPACE
PATIENT_ID_KV: "\"patientID\"" SPACE ":" SPACE STRING
start: SPACE  "{" SPACE DEVICE_ID_KV "," SPACE PATIENT_ID_KV "," SPACE METRICS_KV "," SPACE TIMESTAMP_KV "}" SPACE FENCE?
SPACE: /[ \t\n\r]/*
STRING: "\"" CHAR* "\"" SPACE
TIME: (/[01]/ /[0-9]/ | "2" /[0-3]/) ":" /[0-5]/ /[0-9]/ ":" /[0-5]/ /[0-9]/ ("." /[0-9]/{3,3})? ("Z" | ("+" | "-") (/[01]/ /[0-9]/ | "2" /[0-3]/) ":" /[0-5]/ /[0-9]/)
TIMESTAMP: DATE_TIME_STRING
TIMESTAMP_KV: "\"timestamp\"" SPACE ":" SPACE TIMESTAMP
FENCE: "```"
