%llguidance {}

ASSET_TYPE_KV: "\"assetType\"" SPACE ":" SPACE STRING

CHAR: /[^"\\\x7F\x00-\x1F]/
     | /[\\]/ (/["\\bfnrt]/ | "u" /[0-9a-fA-F]/{4,4})

DECIMAL_PART: /[0-9]/{1,16}
INTEGER: "-"? INTEGRAL_PART SPACE

INTEGRAL_PART: /[0]/
     | /[1-9]/ /[0-9]/{0,15}

LEASE_TERM_KV: "\"leaseTerm\"" SPACE ":" SPACE INTEGER
LESSEE_NAME_KV: "\"lesseeName\"" SPACE ":" SPACE STRING
MONTHLY_PAYMENT_KV: "\"monthlyPayment\"" SPACE ":" SPACE NUMBER
NUMBER: "-"? INTEGRAL_PART ("." DECIMAL_PART)? (/[eE]/ /[-+]/? INTEGRAL_PART)? SPACE
start: SPACE  "{" SPACE LESSEE_NAME_KV "," SPACE ASSET_TYPE_KV "," SPACE LEASE_TERM_KV "," SPACE MONTHLY_PAYMENT_KV "}" SPACE FENCE?
SPACE: /[ \t\n\r]/*
STRING: "\"" CHAR* "\"" SPACE
FENCE: "```"
